repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.1.4
    hooks:
    -   id: isort

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
