repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: check-ast
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
